---
title: "PM566 Final Project"
author: "Christina Lin"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---

# Exploring Cytochrome P450 Enzymes Found in the Human Brain

This project is based on my PhD thesis exploring the enzymes in the brain that can produce the neurosteroid pregnenolone from cholesterol. In classical steroid-producing organs such as the adrenals, pregnenolone is metabolized from cholesterol by the cytochrome P450 (CYP450) enzyme CYP11A1 (see [Lin & Papadopoulos, 2021](https://pubmed.ncbi.nlm.nih.gov/34015388/) for review). However, CYP11A1 protein is difficult to detect in the brain and preliminary experiments have revealed that a potential alternate pathway not involving CYP11A1 is used by human brain cells to produce pregnenolone. Therefore, this project will analyze known CYP450s in the UniProt database as well as microarray data from the Allen Brain Atlas to answer 2 main questions: 1) Which CYP450 enzymes are expressed in the brain and what are their expression levels? 2) Which of those CYP450 enzymes are involved in cholesterol/steroid metabolism? 
